### ISSUE TITLE
Unsolvable tasks are solvable assuming correct task

### ISSUE THREAD

**Issue by ozppupbg** [neoneye/arc-dataset-collection#1]
Hello,

these unsolvable examples:
https://github.com/neoneye/arc-dataset-collection/blob/f9e4171b6987c118f158c775c05a4b2bc50c361b/dataset/1D-ARC/readme.md?plain=1#L10-L12
Are actually correct and solvable, if you do not assume a counting task, but an odd-even task (as I assumed by the file name and confirmed by this example in the original repo: https://github.com/khalil-research/1D-ARC/blob/542efdb83cd23c519dd2a4d0563070f1a7c9b938/ds_visualize/Recolor_by_Odd_Even.png).

**Comment by neoneye** [comment]
You are right.

I forgot to update the readme. These tasks are good. 

https://github.com/khalil-research/1D-ARC/issues/3
https://github.com/khalil-research/1D-ARC/issues/4
https://github.com/khalil-research/1D-ARC/issues/5
